/**
 * Shopify Variant ID Map
 *
 * Maps tier × size × color to Shopify variant IDs.
 * AUTO-GENERATED by scripts/update-variant-map.mjs — do not edit by hand.
 * Last updated: 2026-04-05T06:01:30.574Z
 *
 * To update: node scripts/update-variant-map.mjs '<json>'
 */
export const VARIANT_MAP: Record<string, Record<string, Record<string, string>>> = {
    full: { // DreamPlay Premium Bundle
        'DS5.5': { 'Black': '53270473867578', 'White': '53270473900346' },
        'DS6.0': { 'Black': '53270473933114', 'White': '53270473965882' },
        'DS6.5': { 'Black': '53270473998650', 'White': '53270474031418' },
    },
    solo: { // Keyboard Only
        'DS5.5': { 'Black': '53088921583930', 'White': '53088921616698' },
        'DS6.0': { 'Black': '53088921649466', 'White': '53088921682234' },
        'DS6.5': { 'Black': '53088921715002', 'White': '53088921747770' },
    },
    reservation: { // Lock My Spot ($99)
        'DS5.5': { 'Black': '', 'White': '' },
        'DS6.0': { 'Black': '', 'White': '' },
        'DS6.5': { 'Black': '', 'White': '' },
    },
    reserve50: { // Reserve (50%)
        'DS5.5': { 'Black': '', 'White': '' },
        'DS6.0': { 'Black': '', 'White': '' },
        'DS6.5': { 'Black': '', 'White': '' },
    },
};
